### ISSUE TITLE
Requests with no auth token are authorized

### ISSUE THREAD

**Issue by raphael** [rightscale/jwtauth#3]
If the endpoint requires no scope. Seems like there should be a `else` clause (conceptually) to https://github.com/rightscale/goa-jwtauth/blob/master/new.go#L33-L41 that rejects the request if the token is nil. The middleware code only executes on endpoints that setup a security scheme.

**Comment by cornfeedhobo** [comment]
@xeger Any reason for closing this?

**Comment by raphael** [comment]
@cornfeedhobo fixed by https://github.com/rightscale/jwtauth/pull/4

**Comment by cornfeedhobo** [comment]
Huzzah!
